### ISSUE TITLE
401 Unauthorized and X-Rack-Cache: invalidate, pass

### ISSUE THREAD

**Issue by dnnsldr** [jeremypeter/grunt-litmus#5]
I am having the same issue. I can log into my account with the username and password. I have verified my "Subdomain for API" inside my profile. But each time I run my grunt task I get an error:

Could't authenticate you
Fatal error: 401 Unauthorized

Here is a screenshot of my terminal after running the tast:
![screen shot 2014-10-01 at 4 26 46 pm](https://cloud.githubusercontent.com/assets/224033/4485294/b1974560-49c8-11e4-9438-bddd10583efa.png)

I am not sure what is causing this. I am only testing on two clients: iphone5 and chromegmailnew because they usually don't have issues on the litmus site being down.

The URL that I am using in my grunt options is: https://mysubdomainAPIname.litmus.com

**Comment by jeremypeter** [comment]
Are you able to login with your username and password when you use the url in the browser?

**Comment by dnnsldr** [comment]
it redirects to: https://riester.litmus.com/sessions/new but yes I can log in

**Comment by jeremypeter** [comment]
Ok, are there any extra spaces/characters that might have accidentally been added to the `options.username` and `options.password` properties?

**Comment by dnnsldr** [comment]
No. No extra spaces at all.

**Comment by jeremypeter** [comment]
Are you able to access it from the command line: 

```
curl -u username:password http://companyname.litmus.com/tests.xml
```

That should return a bunch of xml data.

**Comment by dnnsldr** [comment]
I get this error:

syntax error near unexpected token `)'

I guess it doesn't like the ')' in my password!

**Comment by jeremypeter** [comment]
That sucks, so if you removed the ')', it worked?

**Comment by dnnsldr** [comment]
So I entered a new password so that it didn't have any ')' in it. Did the curl command you stated and this is what I got back:

Enter host password for user 'aperkel@riester.com':
curl: (6) Could not resolve host: ****_mypasswordhere**_*\*  (this is where is just listed my password)

Also, even with the curl statement having my password it still asked for it at the command prompt. Just FYI. Any thoughts?

**Comment by dnnsldr** [comment]
The curl statement works! But I can't get the grunt task to work. Gives me a:

Fatal error: 500 Internal Server Error

**Comment by jeremypeter** [comment]
Sorry, been real busy. What did you do to get the curl statement to work? Also, what version of grunt-litmus are you using?

**Comment by dnnsldr** [comment]
I was missing the : between the username and password

I am using grunt 0.4.5

**Comment by jeremypeter** [comment]
What version of grunt-litmus? You can find that in your package.json or node_modules/grunt-litmus/package.json. 
You're still getting a 500 error correct?

**Comment by dnnsldr** [comment]
Grunt Litmus version is 0.1.6
Yeah, still getting the 500 error

**Comment by dnnsldr** [comment]
Here is a snippet of the grunt.js

test: {
            src: ['dist/email-inline.html'],
            options: {
                subject: 'TEST - <%= projectName %>',
                username: '<%= litmusUser %>',
                password: '<%= litmusPassword %>',
                url: 'https://<%= litmusDomain %>.litmus.com',
                clients: [<%= _.words(litmusClients) %>]
            }
        }

This uses a generator. The end grunt file has all the necessary elements in it the way that it should.

**Comment by jeremypeter** [comment]
Have you tried hardcoding the username and password instead of using the template tags?

**Comment by dnnsldr** [comment]
Yes I have.

**Comment by jeremypeter** [comment]
Would you be able to paste your entire gruntfile? So I can try and duplicate the issue

**Comment by dnnsldr** [comment]
Here is a link to the github repo that has the generator. Just look in the `app` folder

https://github.com/dnnsldr/yeoman-ink-me-generator

**Comment by jeremypeter** [comment]
Fixed in `v0.1.8`
I was able to replicate the issue when I used your generator. There was an issue with one of the methods of the xmlbuilder module. Basically wasn't compiling the xml data properly. Update and let me know if everything works for you.

**Comment by dnnsldr** [comment]
That did it! Generator works perfectly. I'll be packaging and sending it up to NPM. Nice job on the grunt-litmus!

**Comment by jeremypeter** [comment]
Sweet! Thank you!

**Comment by jeremypeter** [comment]
Fixed https://github.com/jeremypeter/grunt-litmus/commit/bfbfd4aad8bb6d28800c29a4645ad4c54476c352
